### ISSUE TITLE
No usar tantos selectores por tag y usar clases o IDs

### ISSUE THREAD

**Issue by guillermoparral1995** [gquintela/blog#3]
Es buena práctica usar classes o IDs en los elementos del HTML para después referenciarlos en el CSS. Si bien técnicamente funciona si los referencias por tag, es desprolijo y te puede generar quilombo a medida que se agrega más contenido. Ponele que zafa en elementos HTML que son súper semánticos y que no se deberían repetir nunca (por ej. `header`, `footer`, `main`, `nav`, etc.) pero igual a lo sumo les pondría un ID.

P.D.: el ID es único en todo el HTML. Técnicamente puede haber elementos en un mismo HTML con ID repetido pero está **mal**. Para cosas repetidas, usá classes

**Comment by gquintela** [comment]
copiado.
